name: Base
main: me.Kjordo711.Base.Base
version: 0.1
commands:
    dpickaxe:
      description: command
      usage: /<command>
    bpickaxe:
      description: command
      usage: /<command>

